name: Manubot
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
      SPELLCHECK: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # fetch entire commit history to support get_rootstock_commit
          fetch-depth: 0
      - name: Set Environment Variables
        run: |
          TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
          echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
          echo "TRIGGERING_SHA: $TRIGGERING_SHA"
          DEFAULT_BRANCH=$(git remote show origin | grep --perl-regexp --only-matching "(?<=HEAD branch: ).+")
          echo "DEFAULT_BRANCH=${DEFAULT_BRANCH}" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH_REF=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV
          echo "DEFAULT_BRANCH=$DEFAULT_BRANCH"
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ci/cache
          key: ci-cache-${{ github.ref }}
          restore-keys: |
            ci-cache-${{ env.DEFAULT_BRANCH_REF }}
      - name: Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Install Spellcheck
        shell: bash --login {0}
        run: |
          if [ "${SPELLCHECK:-}" = "true" ]; then
            bash ci/install-spellcheck.sh
          fi
      - name: Build Manuscript
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript-${{ github.run_id }}-${{ env.TRIGGERING_SHA_7 }}
          path: output
      - name: Deploy Manuscript
        if: github.ref == env.DEFAULT_BRANCH_REF && github.event_name == 'push' && !github.event.repository.fork
        env:
          MANUBOT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
          CI_BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
          CI_JOB_WEB_URL: https://github.com/${{ github.repository }}/runs/${{ github.run_id }}
        shell: bash --login {0}
        run: bash ci/deploy.sh
        
        
        
        
        
        The article was written in 1984. It was the about this experiments that were conducted on some isolated village. The villages in (Lulbushki) a was located in the mountaineous region and well built yak roamed the pastures. The inhabitants in Lulbushki depended of the pastures. On 25st of Nvember 1984, some of the yak were rounded up in acordance to the new animal husbandry law of Peking and informtion about what would be done was announced  The yak were coloured white to distinguished them but it was hard to make out teh difference. They were terrified and could possibly have undergone trauma. The yak like to roam freely in nature and do grazing in pastures with their herdsmen guarding them. The herdsmen understand how valuable theur yak are to they. However, they may end up to sell them
